### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by brett-stephen** [a-team-DB/Auto-Web-DB#2]

**Comment by AlexanderBaruta** [comment]
I've downloaded the WAMP server recommended. I'll be working on the database tomorrow after class

**Comment by sherridgeberry** [comment]
@AlexanderBaruta i started a few tables yesterday. I will try to find the files on my local here and include them to see if they are of any use. MAMP offers a DB creation GUI if I was doing everything right.

**Comment by sherridgeberry** [comment]
@AlexanderBaruta we are stuck in the development of the php code until we get the finalized db files.

**Comment by AlexanderBaruta** [comment]
The file should be in the drive.
