### ISSUE TITLE
Unclear design around employees, and sales

### ISSUE THREAD

**Issue by brett-stephen** [a-team-DB/Auto-Web-DB#6]

**Comment by brett-stephen** [comment]
The way employee is currently defined in the table doesn't work well, we need to figure out how to fix that.

**Comment by brett-stephen** [comment]
instead, employees will only have _last name, first name, employeeID and a phone# _ . This should make things a bit more simple, but when we meet up we can discuss this further,

**Comment by sherridgeberry** [comment]
that sounds good. I think I was overthinking it a little bit when doing the original drawings. I will make the updates to the ER Diagram.

**Comment by sherridgeberry** [comment]
E-R Diagram has been updated and report updated to reflect the changes.
