### ISSUE TITLE
Warranty Total & Monthly Cost

### ISSUE THREAD

**Issue by brett-stephen** [a-team-DB/Auto-Web-DB#7]
Are we calculating the total/ monthly cost of the warranties in mysql or php or JS? idk

**Comment by sherridgeberry** [comment]
my understanding of this whole thing is that as we add each coverage to the warranty, the total cost adds itself up like a point of sale at the grocery store. We then have a total cost. The warranty itself would have a length of 12/24/36 months with which we can derive the monthly cost that would be printed in the report.
